### ISSUE TITLE
Low resolution on Windows with high-DPI screens

### ISSUE THREAD

**Issue by aeickhoff** [citybound/citybound#109]
Apparently DPI-scaling is applied and a low-resolution window size reported to the game, resulting in a low-resolution frame buffer.

Workaround is to disable DPI scaling completely via the .exe's properties, but then text is tiny.

**Comment by hubble618** [comment]
Also, its even more pixelated on 4k monitors.

**Comment by aeickhoff** [comment]
Does the workaround fix it for you as well?

**Comment by hubble618** [comment]
![untitled](https://cloud.githubusercontent.com/assets/24769061/22535849/752dd980-e8c3-11e6-9d77-f24424d6da0e.png)
No. This was actually an issue since the first release, I just didn't bother to post about it yet.

If you take that image and zoom all the way in using gimp, paint, or something, you'll notice how each pixel is actually 2 pixels wide and high. If I zoom that image to 50%, it looks really nice. If you are on 1080p, then you'll have to scale that image to 200% to see what I see. Notice at 200%, how on the bottom taskbar pixelation isn't visible. I think this will be an issue for anything higher than 1080.

Since you are already on this issue, you may want to add [resolution support for up to 8k](https://en.wikipedia.org/wiki/List_of_common_resolutions), to future proof, just it in case.

**Comment by aeickhoff** [comment]
This will be obsolete with the web client.
