### ISSUE TITLE
Come up with target resource values, kinds of businesses and activities

### ISSUE THREAD

**Issue by aeickhoff** [citybound/citybound#152]
- [ ] Invent target resource values for families
- [ ] Invent kinds of businesses to cover basic resource needs #148
- [ ] Invent activities to cover all necessary resource trades
- [ ] Invent target resource values for businesses
- [ ] Balance activity resource fulfillment/depletion rates with target resource values

**Comment by mallenwho** [comment]
as far as our "food" supply chain goes, we can do different permutations on that.

We have fruits and vegetables, which mostly go straight from farm to store. They might go to a processing plant for other goods.
Cereals like wheat or corn have to get processed first.
Meat can use pasture or cereals, turn into animals, which have to be transported to an abattoir to be processed. They might get processed further but most of it heads straight to the shops.

This sounds like enough industry to keep a large town going.

**Comment by AzemOcram** [comment]
Here are the resource chains I propose

I) Fields
1. Produce (fruits and vegetables)
(a) Direct to commercial
(b) Canned at Food Processor
2. Grains
(a) Dried and packaged (minimally processed whole grains) on site
(a) Milled 
3. Meat
(a) Direct to commercial
(b) Sent to food processors
(optional) 4. Dairy
(a) Direct to commercial
(b) Sent to creamery
5. Fibers
(a) Textile Mills
6. Working Forests
(a) Lumber Mills

II) Industry
1. Food Processors
2. Grain Mills 
(a) Sent to Bakeries
(b) Sent to Cereal Mills
(c) Sent to Food Processors
3. Textile Mills
(a) Direct to commercial (yardage stores)
(b) Sent to tailors and clothing factories
(c) Sent to Furniture Factory
4. Lumber Mills
(a) Direct to commercial (hardware stores)
(b) Sent to Furniture Factory
5. Manufacturers (for each consumer good)
(a) Imports metal, plastic, and/or lumber
(b) Ships consumer goods to commercial

III) Commerce
1. Offices 
(a) provide Office Services/Logistics to Industry, increasing taxable income
2. Shops
(a) Sell food, clothing, furniture, or consumer goods
(b) Malls have multiple shops
3. Restaurants
(a) Provide food and entertainment but charge more per unit of food
4. Venues
(a) Provide entertainment (can be of certain "flavors" such as sports, cultural, excitement)
(b) Some provide Social Life

**Comment by mallenwho** [comment]
A couple of additions to a much more fleshed out supply chain:

1) Grains go to pasture (meat) too. 
2) The pasture either goes to the creamery (dairy) or must go to an abattoir. Then, on to food processors or direct to commercial
3) while not explicitly included, the milled grains must go to food processing (or bakery), whether they end up as packaged cereals, or a more complex good.
4) The idea that drying cereals on site indicates that they are stored, just like IRL! I would love to see cereal farms being able to hold silos of inventory of grain, to tide them over bad seasons or to distribute as necessary (could help balance ebb and flow of the economy too)
5) Eventually we can see lumber going to other things. Paper mills (to office supply stores, along with commercial offices and other places), woodchip or firewood (which could be a resource down the line), sawdust and woodchip as bulk exports overseas. Eventually, i'd die to see bulk shipping as part of major harbours, along with regular container shipping.
6) Offices definitely enhance large industries and businesses, but there are plenty of independant offices too. Legal, IT, finance and accounting, education, engineering, other consultants. 
7) Full list of shops so far is supermarket, greengrocer (just produce), butcher (just meat), bakery, farmers' market (?) clothing store, furniture store (If we get lumber), consumer goods store (which to be honest, most home improving goods nowadays are going to be electronics), hardware store or landscaping store?
8) resturaunts are good. Food, as well as luxury good, leisure, entertainment, and any other ambiance thing we can think of.
9) I'd also like to include fast food! they can do little money for food, but with adverse physical health. Forces them to do excersise later (which I think is the only way to improve health so far)
10) building on that, we could add a very simple clinic, that customers exchange money for better health, with immediate effects.

Great list. Very little to contribute.

**Comment by AzemOcram** [comment]
Thanks for the input, mallenwho. I tried to make the list a little more understandable.
RE: Your list of suggestions
1. Good idea
2. I thought that butchers and abattoirs could be combined while I knew that dairy livestock is different from meat livestock.
3. It is explicitly included in my list under Industry
4. That is a great idea and I had that in mind. I hope it can be implemented
5. Good idea! I might try to mod that in once the required systems are officially in place (March, perhaps)
6. Good idea to have high wealth residential could demand office services too, not just industry.
7. The full list of shops in the mid-term is supermarket (all foods, plus possibly appliances), department store (clothing and furniture), electronics store, and bakery. That is unless you want to break things up into 1 resource per shop, then supermarkets would be like malls because they would have a greengrocer, bakery, creamery, butcher, and appliance store and a department store would have a clothier and a furniture store.
8. Food, entertainment (same thing as leisure), luxury, and environment/art+comfort (2 subcategories)
9. Also, lack of nutrition means that fast food wouldn't satisfy hunger as long. Maybe have fast food have a time modifier?
10. If health is going to be in the basic release, that would make clinics a requirement.

Full list of zones with associated buildings:
1. Fields (Produce, Grains, more down the line)
2. Industry (food processor, flour mill, electronics manufacturer, more down the line)
3. Commercial (supermarket, bakery, electronics store, theater (entertainment), restaurant, bar (social), mall, more down the line)
4. Office (logistics office, services office)
5. Residential (house, apartment)
6. Mixed (R+C (apartment over shops), C+O (shops+offices), O+I (warehouses, offices, and factories), C+I (light industry, warehouse stores, and factory stores)
7. Government (clinic, police department)

Industrial bakeries would grow in C+I zones, so would stores like IKEA.

**Comment by aeickhoff** [comment]
Superseded by #164

**Comment by mallenwho** [comment]
Here's that graph i was drawing at the end of the most recent live stream. It sums up the resource chains that would exist in the game. What to call the resources i didn't decide. I'm just showing what goes where. Broadly speaking, there's one system for food, and one system for goods. Each system is also broken down into origin of resource (tier 1), which can all be exported; a production node (tier 2), all of which can also be exported and of which constructs conventional industry; and a level of consumption (tier 3) which is retail, offices, and services. Tier 3 doesn't export. 
Many of these could probably have several competing businesses, like grocery stores, occies (different types) or food processors. Others would be quite universal and singular, like paper mills or abattoirs. Carpenters can probably be removed safely, as could cafes.

Doesn't include other services such as clinics.

![resource chain 1](https://user-images.githubusercontent.com/25683627/28380055-383eca1a-6cf9-11e7-8f34-8ef885ed7b11.jpg)

**Comment by aeickhoff** [comment]
That actually puts things really nicely into perspective!!
