### ISSUE TITLE
CI is failing on rustfmt in lane_stroke.rs

### ISSUE THREAD

**Issue by Herbstein** [citybound/citybound#173]
To put it bluntly: @aeickhoff, are you running rustfmt on your local copy before pushing? I've experienced several times that the format-on-save option would change files in my local files. It's kind of an issue having the CI check formatting if we aren't formatting our code when pushing.

**Comment by aeickhoff** [comment]
I use the format on save as well but usually I do an additional manual check before pushing (since it sometimes fails to make a line short enough), but right now I'm working super fast in a WIP branch that I don't expect anyone else to work on in between, I'll make sure it's fine once the PR is ready!

**Comment by Herbstein** [comment]
Sounds reasonable. Just wanted to check up on that. It's a pain if there is unrelated formatting changes in a commit - especially if it's the whole file.
