### ISSUE TITLE
Separating Kay into its own crate + project

### ISSUE THREAD

**Issue by teovoinea** [citybound/citybound#209]
This issue is for discussing the separation of [Kay](https://github.com/citybound/citybound/tree/master/engine/kay) from the core engine.

Topics to discuss:

- [ ] Should Kay stay in the same repo or a new one?
- [ ]  Any additional documentation required?

**Comment by aeickhoff** [comment]
Regarding the first point: separate repo should be fine and was already discussed in #204. But then all the dependencies (`compact`, `chunked`) and `kay_codegen` should also get separate repos.

Kay itself is more or less documented, `kay_codegen` is not at all documented though, and would really benefit from some usage examples.

I don't have time for this before the next prototype release (Oct. 31st), but if you or anyone wants to tackle some documentation before then, just in this repo, I can accept PRs.

**Comment by est31** [comment]
@aeickhoff wondering, which licensing model do you envision for Kay? Right now it is part of citybound and covered by its license, so it is AGPL licensed at the moment.

For most game developers, anything copyleft related is a thing they don't really like, as game code is usually proprietary.

Therefore there are two models:

* Keep the license of Kay as AGPL, and offer separate agreements for people who want to use Kay or its dependencies in their (proprietary) games.
* Relicense Kay and its dependencies to something permissive, like the dual MIT/Apache-2.0 license that is the standard in the Rust ecosystem. As you already have a CLA set up, it should be easy in the future to move code from the AGPL licensed part of your codebase to Kay (this is a real issue if you lack a CLA).

**Comment by aeickhoff** [comment]
Since people raised this issue on the Rust subreddit again, and there seems to be moderate interest, let me give you a quick update:

- I wouldn't mind separating Kay and licensing it as MIT/Apache-2.0
- Kay is written generically of course, but many of it's design goals (as well as non-goals) directly result from Citybound's requirements and might be an obstacle for other users
  - for example: all actor state and messages must derive `Compact`
- I certainly do not have the time to maintain and document Kay beyond my own needs, but I would be open to accept help and give initial assistance to any interested contributors

**Comment by aeickhoff** [comment]
Just a heads up: I just extracted kay (and all it's dependencies) into a separate repo and published it on crates.io, even though everything is experimental. It's very barebones now, but I'll flesh out documentation and disclaimers soon.

https://github.com/aeickhoff/kay
