### ISSUE TITLE
Binary not running (anymore) on macOS

### ISSUE THREAD

**Issue by chdudek** [citybound/citybound#34]
I downloaded the app bundle and started it once without problems. 
Now I can't open it anymore, I just get a process running at almost 100%. Starting the binary inside the package using the terminal gives no output.

Running from source works fine, self compiled binary works fine as well!

OS: macOS Sierra 10.12.2

**Comment by garddun** [comment]
I have the same problem. Louched it ones, and now it dosent work anymore. What to do?

**Comment by mhabegger** [comment]
Same behaviour here.
Deleted the applications saved data however makes it start again :

```
rm -r "/Users/<username>/Library/Saved Application State/co.aeplay.citybound.savedState/"
```

**Comment by chances** [comment]
For easier copy-pasta:
```
rm -r "/Users/$USER/Library/Saved Application State/co.aeplay.citybound.savedState/"
```

**Comment by aeickhoff** [comment]
I'm new to .app bundling, anyone have an idea what could cause this? I don't know why it creates saved state...

**Comment by aeickhoff** [comment]
This is such a tough nut, so when Citybound is quit abnormally (force quit, logout, ...) it saves its window state into Saved Application State/co.aeplay.citybound.savedState/, as Cocoa apps apparently do by default, but then (this is my guess) when you launch it again, it can't deal with this restore information.

The problem is that all the cocoa code is hidden deep in the `glutin` dependency, so I can't just mark the window which is created as non-restorable that easily.

Doing more research...

**Comment by aeickhoff** [comment]
Could you please try if the same still happens with this bundle:
[citybound.app.zip](https://github.com/citybound/citybound/files/694861/citybound.app.zip)

**Comment by chances** [comment]
@aeickhoff Issue seems resolved on my end.

**Comment by aeickhoff** [comment]
Thank you!
