### ISSUE TITLE
Will multi-language be suppot?

### ISSUE THREAD

**Issue by sakurayang** [citybound/citybound#345]

**Comment by aeplay** [comment]
yes, which would you like to see?

**Comment by MiniDigger** [comment]
I guess translations could be easily crowdsourced (I used poeditor which is free for 1k strings and can import/export directly to github https://poeditor.com/pricing/) so that you don't need to hardcode any languages and whenever somebody comes around and wants a new language and it gets accepted by a few community members you can just pull it in.
