### ISSUE TITLE
the error 

### ISSUE THREAD

**Issue by windsor0144** [citybound/citybound#371]
error: proc-macro derive panicked
 --> cb_server/browser_ui_server.rs:4:10
  |
4 | #[derive(RustEmbed)]
  |          ^^^^^^^^^
  |
  = help: message: #[derive(RustEmbed)] folder 'cb_browser_ui/dist/' does not exist. cwd: '/Users/user/citybound'

error: aborting due to previous error

error: could not compile `citybound`.

To learn more, run the command again with --verbose.

**Comment by aeplay** [comment]
Did you compile Citybound according to these instructions? https://github.com/citybound/citybound/blob/master/CONTRIBUTING.md#compiling-and-running-citybound-yourself

Because it looks like you are trying to build a bundled version of the simulation server, and that requires the browser ui to already be built. But you shouldn't even need that

**Comment by windsor0144** [comment]
now it is working, thx for help
